### ISSUE TITLE
With Valid pad mode, the output dimension don't match the input dimensions

### ISSUE THREAD

**Issue by anshkapil** [computationalpathologygroup/hooknet#1]
When I compile the model with "valid" padding mode, the output shape is (None, 70, 70, n_classes) with the default paramters. This seems to be due to the conv2D layer after upsampling which reduces the dimension of the upsampled layer by size of 2.

With the "same" padding, the network compiles correctly.

Is there anything I need to take care of for getting the model with "valid" padding successfully?

**Comment by martvanrijthoven** [comment]
The output shape (None, 70, 70, n_classes)  is expected (and correct) when using valid padding mode. 
With valid padding mode, the 2d convolutional operator applied to the image and feature maps will not add any extra pixels to the input. With a filter size of 3x3 and a stride 1, this means that for, each 2d convolution, 2 pixels for the x and y dimensions are lost. When using same padding 2 extra pixels ( left, right for the x dimension and top bottom for the y dimension) are added. These pixels are artificial (e.g., black pixels) which can introduce border artifacts. Hence i would recommend to use valid padding

**Comment by anshkapil** [comment]
Thanks for the quick response, in that case, how do we handle the ground truth masks? Do we naively resize them to (70, 70) px size? @martvanrijthoven

**Comment by martvanrijthoven** [comment]
Yes, you are right. However i have not included that code in this repo. You can use/change the following code to your liking:

    def fit_data(mask, output_shape):

        # if 'same' padding
        if (mask.shape[0] == output_shape[0]) and (mask.shape[1] == output_shape[1]):
            return mask

        cropy = (mask.shape[0] - output_shape[0]) // 2
        cropx = (mask.shape[1] - output_shape[1]) // 2
 
        # mask 
        if len(mask.shape) == 2:
            return mask[cropy:-cropy, cropx:-cropx]

        # one-hot-encoded mask
        if len(mask.shape) == 3:
            return mask[cropy:-cropy, cropx:-cropx, :]
